# Generated by Django 3.2.9 on 2021-11-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(help_text='邮箱', max_length=100, null=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text='密码', max_length=255, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(help_text='姓名', max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(help_text='手机号', max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
