# Generated by Django 3.2.9 on 2022-01-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='circle_url',
            field=models.TextField(null=True, verbose_name='头像'),
        ),
    ]
