# Generated by Django 3.2.9 on 2021-11-25 07:55

import college_bbs.common.models.base_models
import college_bbs.common.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user_id', models.BigIntegerField(default=college_bbs.common.models.base_models.get_create_user_id, verbose_name='创建人 ID')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='赞同数')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('parent_comment_id', models.BigIntegerField(null=True, verbose_name='评论id')),
                ('comment_id', models.BigIntegerField(null=True, verbose_name='评论id')),
            ],
            options={
                'db_table': 'child_comment',
                'abstract': False,
            },
            bases=(college_bbs.common.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ParentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user_id', models.BigIntegerField(default=college_bbs.common.models.base_models.get_create_user_id, verbose_name='创建人 ID')),
                ('like_count', models.BigIntegerField(default=0, verbose_name='赞同数')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('post_id', models.BigIntegerField(null=True, verbose_name='帖子id')),
                ('comment_number', models.BigIntegerField(default=0, verbose_name='回复数')),
            ],
            options={
                'db_table': 'parent_comment',
                'abstract': False,
            },
            bases=(college_bbs.common.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user_id', models.BigIntegerField(default=college_bbs.common.models.base_models.get_create_user_id, verbose_name='创建人 ID')),
                ('title', models.CharField(max_length=255, verbose_name='问题标题')),
                ('content', models.TextField(verbose_name='问题内容')),
                ('answer_count', models.BigIntegerField(default=0, verbose_name='回答数量')),
                ('views_count', models.BigIntegerField(default=0, verbose_name='浏览量')),
                ('topic_id', models.BigIntegerField(null=True, verbose_name='话题id')),
            ],
            options={
                'db_table': 'post',
                'abstract': False,
            },
            bases=(college_bbs.common.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user_id', models.BigIntegerField(default=college_bbs.common.models.base_models.get_create_user_id, verbose_name='创建人 ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='话题名字')),
                ('description', models.TextField(null=True, verbose_name='话题描述')),
                ('host_number', models.BigIntegerField(default=0, verbose_name='热度')),
            ],
            options={
                'db_table': 'topic',
                'abstract': False,
            },
            bases=(college_bbs.common.models.deletion.ModelOnDeleteMixin, models.Model),
        ),
    ]
