# Generated by Django 3.2.9 on 2022-01-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='agree_number',
            field=models.BigIntegerField(default=0, null=True, verbose_name='点赞量'),
        ),
    ]
